import { readFileSync, writeFileSync, mkdirSync, cpSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
const root=resolve(import.meta.dirname,'..');
const record=JSON.parse(readFileSync(join(root,'public/fm6.json'),'utf8'));
const source=resolve(process.env.FM6_SOURCE_DIR || join(root,'../agent-synth-magic'));
for(const field of ['name','summary','description','canonical','source','sourceCommit','creator','creatorUrl','poster','posterAlt','datePublished','dateModified','privacy','why']) if(!record[field]) throw new Error(`Missing ${field}`);
const sha=execFileSync('git',['rev-parse','HEAD'],{cwd:source,encoding:'utf8'}).trim();
if(sha!==record.sourceCommit) throw new Error('FM6 source HEAD must match public/fm6.json sourceCommit.');
if(execFileSync('git',['status','--porcelain'],{cwd:source,encoding:'utf8'}).trim()) throw new Error('Build FM6 from a clean source checkout.');
execFileSync('npm',['run','build'],{cwd:source,stdio:'inherit'});
const out=join(root,'public/fm6'); mkdirSync(out,{recursive:true});
for(const dir of ['assets','wasm']) cpSync(join(source,'dist',dir),join(out,dir),{recursive:true,filter:path=>!['.gitkeep','.DS_Store'].includes(path.split('/').at(-1))});
const built=readFileSync(join(source,'dist/index.html'),'utf8');
const assets=[...built.matchAll(/<(?:script[^>]*src="[^"]+"[^>]*><\/script|link[^>]*rel="stylesheet"[^>]*)>/g)].map(match=>match[0]).join('\n');
if(!assets.includes('./assets/')) throw new Error('Expected relative Vite assets.');
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const edgeHtml=record.edges.map(edge=>`<li><a href="${esc(edge.url)}">${esc(edge.name)}</a> — ${esc(edge.note)}</li>`).join('');
const metadata={ '@context':'https://schema.org','@graph':[
 {'@type':'WebApplication','@id':record.canonical+'#instrument',name:record.name,description:record.description,url:record.canonical,image:record.poster,datePublished:record.datePublished,dateModified:record.dateModified,applicationCategory:'MultimediaApplication',operatingSystem:'Web browser',isAccessibleForFree:true,author:{'@id':record.creatorUrl+'/#person'},isPartOf:{'@type':'WebSite',name:'Contraptions',url:record.edges[0].url},featureList:record.features,mentions:record.edges.slice(1).map(edge=>({'@type':'CreativeWork',name:edge.name,url:edge.url,description:edge.note}))},
 {'@type':'Person','@id':record.creatorUrl+'/#person',name:record.creator,url:record.creatorUrl,sameAs:['https://x.com/noisegroove','https://github.com/whiddershins']}
]};
const title=record.name+' — '+record.creator;
const css=`.fm6-intro,.fm6-guide{max-width:1476px;margin:auto;padding:28px 42px;color:#27332d;font-family:system-ui,sans-serif}.fm6-intro{border-bottom:1px solid #d7dacf}.fm6-intro nav,.fm6-guide nav{display:flex;gap:18px;flex-wrap:wrap;font-size:12px}.fm6-intro a,.fm6-guide a{color:#155e52;text-underline-offset:3px}.fm6-intro h1{white-space:normal;font-size:clamp(26px,4vw,44px);letter-spacing:-1.4px;margin:24px 0 12px}.fm6-intro .lede{font-size:18px;line-height:1.55;max-width:800px}.fm6-intro p,.fm6-guide p,.fm6-guide li{line-height:1.65}.fm6-intro .start{font-size:14px;max-width:900px}.fm6-guide{border-top:1px solid #d7dacf}.fm6-guide h2{font-size:24px;margin:22px 0}.fm6-guide h3{font-size:16px}.fm6-guide .guide-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px 32px}.fm6-guide .guide-grid p{font-size:14px}.fm6-guide ul{padding-left:20px}.fm6-guide .context{max-width:930px}.fm6-guide .meta{font-size:12px;color:#647067}.fm6-guide details{margin:20px 0}.fm6-guide summary{cursor:pointer;font-weight:600}.fm6-intro .jump{display:inline-block;background:#155e52;color:white;padding:11px 18px;border-radius:5px;text-decoration:none;margin:6px 12px 0 0}@media(max-width:700px){.fm6-intro,.fm6-guide{padding:22px 20px}.fm6-guide .guide-grid{grid-template-columns:1fr}.fm6-intro .lede{font-size:16px}}`;
const intro=`<header class="fm6-intro"><nav><a href="/">← Contraptions</a><a href="${record.creatorUrl}">${record.creator}</a><a href="#fm6-guide">How to play</a></nav><h1>${esc(record.summary)}</h1><p class="lede">${esc(record.description)}</p><p class="start">Choose a starting patch and play a note. Each operator explains what it contributes and gives you a change to try. Keep a chord going on the two keyboards while you shape the tone.</p><a class="jump" href="#app">Play FM / 6 ↓</a><a href="#fm6-guide">Get to know the controls</a></header>`;
const guide=`<section class="fm6-guide" id="fm6-guide" aria-label="FM / 6 guide"><h2>Take a sound apart. Put it back differently.</h2><p>${esc(record.why)}</p><div class="guide-grid">${record.guide.map(item=>`<section><h3>${esc(item.title)}</h3><p>${esc(item.text)}</p></section>`).join('')}</div><details><summary>What’s inside FM / 6</summary><ul>${record.features.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></details><div class="context"><h2>Your sound stays here</h2><p>${esc(record.privacy)}</p><p>Saved patches are specific to the site where you saved them. Moving from the <a href="https://fm6-sound-lab.noisegroove.chatgpt.site/">first FM / 6 site</a>? Use Export JSON there, then Load patch here.</p><p>Touch keyboards support independent fingers and drag glissando. Safari on iPad does not offer Web MIDI; use the touch keyboards there. MIDI and MPE need a supporting browser and permission for your controller. The instrument has sixteen shared voices.</p><h2>Part of the work</h2><ul>${edgeHtml}</ul><p>The source is maintained in a private repository. The <a href="/fm6.json">release record</a> identifies the source revision; the <a href="/fm6.md">text guide</a> describes the instrument.</p><p class="meta">By <a href="${record.creatorUrl}">${record.creator}</a> · Published ${record.datePublished} · ${record.hosting}<br>The engine uses phase modulation for FM synthesis. No model listens to or scores your sound.</p><nav><a href="/">More Contraptions</a><a href="/soundscape-one">Play Soundscape One</a><a href="/llms.txt">Site guide</a></nav></div></section>`;
const metas=[['og:type','website'],['og:site_name','Contraptions'],['og:title',title],['og:description',record.description],['og:url',record.canonical],['og:image',record.poster],['og:image:secure_url',record.poster],['og:image:type','image/png'],['og:image:width',record.posterWidth],['og:image:height',record.posterHeight],['og:image:alt',record.posterAlt]].map(([key,value])=>`<meta property="${key}" content="${esc(value)}">`).join('\n');
const twitter=[['card','summary_large_image'],['site','@noisegroove'],['title',title],['description',record.description],['image',record.poster],['image:alt',record.posterAlt]].map(([key,value])=>`<meta name="twitter:${key}" content="${esc(value)}">`).join('\n');
writeFileSync(join(out,'index.html'),`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f2f1eb"><title>${esc(title)}</title><meta name="description" content="${esc(record.description)}"><link rel="canonical" href="${record.canonical}"><link rel="author" href="${record.creatorUrl}"><link rel="icon" href="/fm6/icon.svg"><link rel="apple-touch-icon" href="/shots/fm6-touch.png">${metas}${twitter}<script type="application/ld+json">${JSON.stringify(metadata).replaceAll('<','\\u003c')}</script>${assets}<style>${css}</style></head><body>${intro}<div id="app"></div><noscript><p class="fm6-intro">Enable JavaScript to play the instrument. The guide below is available without it.</p></noscript>${guide}</body></html>`);
writeFileSync(join(out,'icon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="13" fill="#155e52"/><text x="32" y="46" text-anchor="middle" font-family="sans-serif" font-size="44" fill="#f2f1eb">∿</text></svg>');
const card=`<!-- fm6-card:start -->\n<article><h3><a href="/fm6/">${esc(record.name)}</a></h3><p class="blurb">${esc(record.summary)} Start with a bell, a bass or a slowly moving chord. Shape the tone, hold a few notes, and let the operator explanations show you what to try next.</p><a class="shot" href="/fm6/"><img src="${record.poster}" alt="${esc(record.posterAlt)}" width="1200" height="630" loading="lazy"></a><p class="meta"><a href="/fm6/">Play FM / 6</a> · <a href="/fm6/#fm6-guide">How it works</a> · <a href="/fm6.md">md</a></p></article>\n<!-- fm6-card:end -->`;
const indexPath=join(root,'public/index.html');let index=readFileSync(indexPath,'utf8');
index=index.includes('<!-- fm6-card:start -->')?index.replace(/<!-- fm6-card:start -->[\s\S]*?<!-- fm6-card:end -->/,card):index.replace('  <p class="lede">Machines I made.</p>\n  <section>','  <p class="lede">Machines I made.</p>\n  <section>\n'+card);
if(!index.includes('<!-- fm6-card:start -->'))throw new Error('Shelf insertion point missing');writeFileSync(indexPath,index);
const md=`# ${record.name}\n\n${record.summary}\n\n${record.description}\n\nPlay: ${record.canonical}\nCreator: ${record.creatorUrl}\nHosted on ${record.hosting}. Published ${record.datePublished}.\n\n## How to play\n\n${record.guide.map(item=>`### ${item.title}\n\n${item.text}`).join('\n\n')}\n\n## Why\n\n${record.why}\n\n## Features\n\n${record.features.map(item=>'- '+item).join('\n')}\n\n## Privacy and saved patches\n\n${record.privacy}\n\nSaved patches do not automatically transfer between sites. Export JSON on the first site and Load patch here.\n\n## Context\n\n${record.edges.map(edge=>`- [${edge.name}](${edge.url}): ${edge.note}`).join('\n')}\n\n## Source\n\nPrivate repository: ${record.source}\nRevision: ${record.sourceCommit}\nRelease record: https://contraptions.bookofsarth.com/fm6.json\n`;
writeFileSync(join(root,'public/fm6.md'),md);
for(const [file,block] of [['public/llms.txt',`## FM / 6\n${record.description}\n${record.canonical}\nhttps://contraptions.bookofsarth.com/fm6.md\nhttps://contraptions.bookofsarth.com/fm6.json`],['docs/ledger.md',`## FM / 6\n\n- canonical and live: ${record.canonical}\n- source: ${record.source} (private), ${record.sourceCommit}\n- poster: ${record.poster}\n- description: ${record.summary}\n- related: Soundscape One\n- published: ${record.datePublished}\n- syndication: not sent; requires the owner’s instruction`]]) {
 const path=join(root,file);let text=readFileSync(path,'utf8');text=text.replace(/\n<!-- fm6-record:start -->[\s\S]*?<!-- fm6-record:end -->\n?/,'');writeFileSync(path,text+`\n<!-- fm6-record:start -->\n${block}\n<!-- fm6-record:end -->\n`);
}
const sitemapPath=join(root,'public/sitemap.xml');let sitemap=readFileSync(sitemapPath,'utf8').replace(/\s*<!-- fm6:start -->[\s\S]*?<!-- fm6:end -->/,'');sitemap=sitemap.replace('</urlset>',`<!-- fm6:start --><url><loc>${record.canonical}</loc><lastmod>${record.dateModified}</lastmod></url><url><loc>https://contraptions.bookofsarth.com/fm6.md</loc></url><url><loc>https://contraptions.bookofsarth.com/fm6.json</loc></url><!-- fm6:end -->\n</urlset>`);writeFileSync(sitemapPath,sitemap);
execFileSync(process.execPath,[join(root,'scripts/check-fm6.mjs')],{cwd:root,stdio:'inherit'});
console.log(`Prepared ${record.name} from ${sha}.`);
